project:
  type: website

website:
  title: Project Title
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-S24/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\AlgoAces-logo.webp
  favicon: images\AlgoAces-logo.webp    

format:
  html:
    theme: default
      light: lightly
      dark: darkly
    toc: true

execute:
  freeze: auto
