---
title: "Algo Aces Project Proposal"
subtitle: "Proposal"
format: html
editor: visual
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
import pandas as pd
import requests
```

## Dataset

```{python}
#| label: load-dataset
#| message: false
df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")
df.head()


```

### Dataset Description:
The "Fast Food Calories" dataset comprises nutritional information for various food items offered by eight distinct fast-food outlets. Each outlet's menu is detailed, encompassing items such as burgers, fries, beverages, and salads. The dataset includes essential nutritional metrics like calories, fat content, protein, and carbohydrates, allowing for in-depth analysis and comparison of the health implications of different menu choices. 

Provenance:
The dataset's source could be a variety of sources, including research institutions,
open data repositories, or compiled data sets from various sources.

Dimensions:
The dataset likely contains multiple columns representing different attributes of fast food items, 
such as name, restaurant, category, calorie count, fat content, protein content, 
carbohydrate content, etc. The number of rows corresponds to the number of individual fast food items for each restaurant in the dataset.

#### **Why this Dataset:**

Relevance:
Fast food consumption is a significant aspect of modern dietary habits, making this dataset relevant for understanding nutritional patterns and trends.

-> It makes it possible to see how the allocation of calorie counts within various fast food item categories is visualized, providing information about the items' primary tendencies and variability.
-> Making educated dietary decisions is further facilitated by the ability to quickly identify variations in calorie distributions by comparing half violin plots across various fast-food categories.
-> Comparing different fast-food establishments or menu items can be rendered simpler with this sort of visualization portrayal of calorie data, which helps consumers make healthier decisions.
-> Researchers and policymakers can contribute to efforts to promote healthy eating habits in society and increase public knowledge of nutritional value by utilizing fast food calorie data in data visualization initiatives. 

Data Mining Opportunities:
The dataset provides ample opportunities for data mining tasks such as exploratory data analysis.


### Questions

Q1) How many calories areconsumed on average per visit to each restaurant or outlet?
Q2) How do different food item categories vary in protien-fat ratio and do they meet up to the standards of the health metric?


### Analysis plan

Q1:
We will use the function `groupby.describe( )` which includes mean, mode, median, min, and max, to construct a table with summary statistics for each restaurant item in terms of calories.We are going to sum up all the calories for all the items in a restaurant and divide it with no of items gives avg calories gained by a person so we are going to use a half violin plot to showcase this result.

Variables used:

`restaurant`: Name of fast food joint or outlet
`item`: Food item being examined
`total_fat`: The total amount of fat in the food item
`calories`: The number of calories in the food item
`cholesterol`: The amount of cholesterol in the food item


Q2:
For question 2, the relevant columns will be protein, and item. To ensure when proteins and fats, we shall convert them from to calories. Using the protein-fat ratio, we can create a health metric that allows us to if a food item is healthy or harmful. We would like to visualise this using a half violin plot for better understanding of the metrics.

Variables used:

`restaurant`: Name of fast food joint or outlet
`item`: Food item being examined
`total_fat`: The total amount of fat in the food item
`protein`:The amount of protein
